apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaya
  template:
    metadata:
      labels:
        app: yaya
    spec:
      containers:
      - image: okteto.dev/yaya:latest
        name: yaya
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3583d97e-2be7-4812-a2e6-44cdd1451a75"
        - name: Vless_Path
          value: "/jhvtxco548c"
        - name: Vmess_UUID
          value: "3583d97e-2be7-4812-a2e6-44cdd1451a75"
        - name: Vmess_Path
          value: "/kctxrt934x"
        - name: Share_Path
          value: "/v2link"
